<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.k_0r59U' shared service.

return $this->privates['.service_locator.k_0r59U'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\Api\\LoginController::checkLogin' => ['privates', '.service_locator.Sw..Pp5', 'get_ServiceLocator_Sw__Pp5Service.php', true],
    'App\\Controller\\Api\\UserController::register' => ['privates', '.service_locator.Sw..Pp5', 'get_ServiceLocator_Sw__Pp5Service.php', true],
    'App\\Controller\\Api\\LoginController:checkLogin' => ['privates', '.service_locator.Sw..Pp5', 'get_ServiceLocator_Sw__Pp5Service.php', true],
    'App\\Controller\\Api\\UserController:register' => ['privates', '.service_locator.Sw..Pp5', 'get_ServiceLocator_Sw__Pp5Service.php', true],
], [
    'App\\Controller\\Api\\LoginController::checkLogin' => '?',
    'App\\Controller\\Api\\UserController::register' => '?',
    'App\\Controller\\Api\\LoginController:checkLogin' => '?',
    'App\\Controller\\Api\\UserController:register' => '?',
]);
