<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\Api\LoginController' shared autowired service.

include_once $this->targetDirs[3].'/vendor/friendsofsymfony/rest-bundle/Controller/ControllerTrait.php';
include_once $this->targetDirs[3].'/src/Controller/Api/BaseController.php';
include_once $this->targetDirs[3].'/src/Controller/Api/LoginController.php';

$this->services['App\\Controller\\Api\\LoginController'] = $instance = new \App\Controller\Api\LoginController();

$instance->setViewHandler(($this->services['fos_rest.view_handler'] ?? $this->load('getFosRest_ViewHandlerService.php')));

return $instance;
