<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Response\Entity' shared autowired service.

include_once $this->targetDirs[3].'/src/Response/ResponseData.php';
include_once $this->targetDirs[3].'/src/Response/Entity.php';

return $this->privates['App\\Response\\Entity'] = new \App\Response\Entity();
