<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOdh2aS0\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOdh2aS0/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOdh2aS0.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOdh2aS0\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerOdh2aS0\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Odh2aS0',
    'container.build_id' => 'be4ab8c9',
    'container.build_time' => 1570247192,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOdh2aS0');
