<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXtql4vp\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXtql4vp/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXtql4vp.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXtql4vp\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXtql4vp\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Xtql4vp',
    'container.build_id' => '5caff9be',
    'container.build_time' => 1570257230,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXtql4vp');
